-- Create simplified project_progress table for Foreman Analysis
-- This version doesn't require foreign key constraints to existing tables

CREATE TABLE IF NOT EXISTS public.project_progress (
    id bigint generated by default as identity not null,
    project_id bigint null,
    jobcode_id bigint null,
    progress double precision null,
    created_at timestamp with time zone not null default now(),
    constraint project_progress_pkey primary key (id)
) TABLESPACE pg_default;

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_project_progress_project_id ON public.project_progress(project_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_jobcode_id ON public.project_progress(jobcode_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_created_at ON public.project_progress(created_at);

-- Add check constraint to ensure progress is between 0 and 100
ALTER TABLE public.project_progress 
ADD CONSTRAINT chk_progress_range CHECK (progress >= 0 AND progress <= 100);

-- Add comment to the table
COMMENT ON TABLE public.project_progress IS 'Tracks progress percentage for projects and jobcodes in Foreman Analysis';
COMMENT ON COLUMN public.project_progress.progress IS 'Progress percentage (0-100)';
COMMENT ON COLUMN public.project_progress.project_id IS 'Reference to project (can be null)';
COMMENT ON COLUMN public.project_progress.jobcode_id IS 'Reference to jobcode (can be null)';
