create table if not exists public.task_progress (
  id bigint generated by default as identity not null,
  task_id bigint null,
  progress double precision null,
  created_at timestamp with time zone not null default now(),
  constraint task_progress_pkey primary key (id),
  constraint task_progress_task_id_fkey foreign key (task_id) references accubid_breakdowns (id)
) tablespace pg_default;


