#!/usr/bin/env python3
"""
Script to manually create the project_progress table
This script will create the table using Supabase's REST API
"""

import requests
import json

# Supabase configuration
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

def create_table_via_rest():
    """Create table using REST API"""
    try:
        # First, let's try to create a simple table using the REST API
        # This is a workaround since we can't execute raw SQL directly
        
        # Test if we can insert into a table that might exist
        test_data = {
            'project_id': 1,
            'jobcode_id': 1,
            'progress': 50.0
        }
        
        # Try to insert into project_progress table
        response = requests.post(
            f"{SUPABASE_URL}/rest/v1/project_progress",
            headers={
                'apikey': SUPABASE_KEY,
                'Authorization': f'Bearer {SUPABASE_KEY}',
                'Content-Type': 'application/json',
                'Prefer': 'return=minimal'
            },
            json=test_data
        )
        
        if response.status_code == 201:
            print("✅ Successfully inserted into project_progress table")
            return True
        elif response.status_code == 404:
            print("❌ project_progress table does not exist")
            return False
        else:
            print(f"❌ Error: {response.status_code} - {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

def main():
    """Main function"""
    print("🔧 Attempting to create project_progress table...")
    print("=" * 50)
    
    if create_table_via_rest():
        print("✅ Table operation successful!")
    else:
        print("❌ Table operation failed.")
        print("\n💡 Manual steps required:")
        print("1. Go to your Supabase dashboard")
        print("2. Navigate to SQL Editor")
        print("3. Run the following SQL:")
        print("""
CREATE TABLE IF NOT EXISTS public.project_progress (
    id bigint generated by default as identity not null,
    project_id bigint null,
    jobcode_id bigint null,
    progress double precision null,
    created_at timestamp with time zone not null default now(),
    constraint project_progress_pkey primary key (id)
) TABLESPACE pg_default;

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_project_progress_project_id ON public.project_progress(project_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_jobcode_id ON public.project_progress(jobcode_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_created_at ON public.project_progress(created_at);

-- Add constraint
ALTER TABLE public.project_progress 
ADD CONSTRAINT chk_progress_range CHECK (progress >= 0 AND progress <= 100);
        """)

if __name__ == "__main__":
    main()
