#!/usr/bin/env python3
"""
Deployment script for Foreman Analysis functionality
This script creates the necessary database table and sets up the Foreman Analysis page
"""

import streamlit as st
from supabase import create_client
import os

# Supabase configuration
SUPABASE_URL = "https://tgendmgdrljuxxxyynpz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZW5kbWdkcmxqdXh4eHl5bnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjM5MTcsImV4cCI6MjA3MjA5OTkxN30.U6ntaBcINvgUH-UOOybhaUHvuIDfenSDzvgH5OQA3S4"

def create_project_progress_table():
    """Check if project_progress table exists and provide setup instructions"""
    try:
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # Check if table exists
        try:
            result = supabase.table('project_progress').select('id').limit(1).execute()
            print("✅ project_progress table already exists")
            return True
        except Exception as e:
            print("⚠️ project_progress table does not exist")
            print("\n📋 To create the table, run this SQL in your Supabase SQL editor:")
            print("=" * 80)
            print("""
CREATE TABLE IF NOT EXISTS public.project_progress (
    id bigint generated by default as identity not null,
    project_id bigint null,
    jobcode_id bigint null,
    progress double precision null,
    created_at timestamp with time zone not null default now(),
    constraint project_progress_pkey primary key (id)
) TABLESPACE pg_default;

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_project_progress_project_id ON public.project_progress(project_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_jobcode_id ON public.project_progress(jobcode_id);
CREATE INDEX IF NOT EXISTS idx_project_progress_created_at ON public.project_progress(created_at);

-- Add check constraint to ensure progress is between 0 and 100
ALTER TABLE public.project_progress 
ADD CONSTRAINT chk_progress_range CHECK (progress >= 0 AND progress <= 100);
            """)
            print("=" * 80)
            return False
        
    except Exception as e:
        print(f"❌ Error checking project_progress table: {str(e)}")
        return False

def verify_table_structure():
    """Verify the table structure"""
    try:
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # Test inserting a sample record
        sample_data = {
            'project_id': 1,
            'jobcode_id': 1,
            'progress': 50.0
        }
        
        result = supabase.table('project_progress').insert(sample_data).execute()
        
        if result.data:
            print("✅ Table structure verified - sample record inserted")
            
            # Clean up the sample record
            supabase.table('project_progress').delete().eq('id', result.data[0]['id']).execute()
            print("✅ Sample record cleaned up")
            return True
        else:
            print("❌ Failed to insert sample record")
            return False
            
    except Exception as e:
        print(f"❌ Error verifying table structure: {str(e)}")
        print("💡 Make sure the table exists and has the correct structure")
        return False

def main():
    """Main deployment function"""
    print("🚀 Deploying Foreman Analysis functionality...")
    print("=" * 50)
    
    # Step 1: Create the table
    print("Step 1: Creating project_progress table...")
    if create_project_progress_table():
        print("✅ Table creation completed")
    else:
        print("❌ Table creation failed")
        return False
    
    print()
    
    # Step 2: Verify the table
    print("Step 2: Verifying table structure...")
    if verify_table_structure():
        print("✅ Table verification completed")
    else:
        print("❌ Table verification failed")
        return False
    
    print()
    print("🎉 Foreman Analysis deployment completed successfully!")
    print("=" * 50)
    print("You can now use the Foreman Analysis page to:")
    print("- Track task progress (0-100%)")
    print("- Track jobcode progress (0-100%)")
    print("- View progress analytics and charts")
    print("- Update progress in real-time")
    
    return True

if __name__ == "__main__":
    main()
